# Generated by Django 4.1.1 on 2022-10-20 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_employee_club_alter_employee_nation'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='Employee',
        ),
    ]
