# Generated by Django 4.1.1 on 2022-10-20 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_employee_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table=None,
        ),
    ]
