# Generated by Django 4.1.1 on 2022-10-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_employee_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='club',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
