# Generated by Django 4.1.5 on 2023-02-02 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_employee_club_alter_employee_first_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Players',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='product',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
